version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=root
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_NAME=user_api
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm start
    networks:
      - app-network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: user_api
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
